# automatic testing with Travis CI!

os:
  - linux
  - osx

language:
  - node_js

node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - yarn test

  # https://electronjs.org/docs/tutorial/testing-on-headless-ci

notifications:
  email:
    # If you don't want to specify emails here,
    # you can set your email with git config --global user.email
    on_success: change
    on_failure: always
