# automatic testing with Travis CI!

os:
  - linux

language: node_js

node_js:
  - 12

addons:
  chrome: stable
  apt:
    packages:
      - xvfb

services:
  - xvfb

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:'99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - node --version
  - npm --version
  - yarn

script:
  - yarn test

  # https://electronjs.org/docs/tutorial/testing-on-headless-ci

notifications:
  email:
    # If you don't want to specify emails here,
    # you can set your email with git config --global user.email
    on_success: change
    on_failure: always
