os:
  - osx

language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - chmod +x travis-build.sh # give permission to execute
  - ./travis-build.sh
  - yarn
  - rm dictionary.js
  - rm obfuscationMapping.js

script:
  - yarn travis-test

notifications:
  email:
    on_success: change
    on_failure: always
