# automatic testing with Travis CI!

language:
  - node_js

node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn

script:
  - yarn test

  # https://electronjs.org/docs/tutorial/testing-on-headless-ci

notifications:
  email:
    # If you don't want to specify emails here,
    # you can set your email with git config --global user.email
    on_success: change
    on_failure: always
