# automatic testing with Travis CI!

os:
  - osx

language: node_js

node_js:
  - "lts/*"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - travis-build.sh
  - yarn

script:
  - yarn test

notifications:
  email:
    # If you don't want to specify emails here,
    # you can set your email with git config --global user.email
    on_success: change
    on_failure: always
