os:
  - osx

language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - mv dictionary.js dictionary_disabled.js;
  - mv obfuscationMapping.js obfuscationMapping_disabled.js

before_script:
  - chmod +x travis-build.sh # give permission to execute
  - ./travis-build.sh
  - yarn

script:
  - yarn travis-test

notifications:
  email:
    on_success: change
    on_failure: always
